Controllers/EmployeeDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IdentityManagement;
using IdentityManagement.Models;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;

namespace EmployeeDataController.Controllers
{
    [Authorize]
  
    public class EmployeeDataController : Controller
    {
        private readonly EmployeeDataDbContext database;
        private readonly IWebHostEnvironment _environment;
       

        public EmployeeDataController(EmployeeDataDbContext context, IWebHostEnvironment environment)
        {
            database = context;
            _environment = environment;
        }

       public async Task<IActionResult> Profile(){ 
        Console.WriteLine("user:"+Database.mail);
        var empolyees = await database.Employeess.Where(b=>b.UserID ==Database.mail).ToListAsync();
        return View(empolyees);
        }
        
  
        [HttpGet]
         
        [Route("EmployeeData/Index")]
        
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)

        {



            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null )
            {
                pageNumber = 1;
            }
           
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;


            var list = from selectedlist in database.Employeess
                     select selectedlist;

            if (!String.IsNullOrEmpty(searchString))
            {
                list = list.Where(selectedlist => selectedlist.UserID.Contains(searchString) || selectedlist.Name.Contains(searchString)
                                       || selectedlist.TeamName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    list = list.OrderByDescending(selectedlist => selectedlist.TeamName);
                    break;
                case "Date":
                    list = list.OrderBy(selectedlist => selectedlist.DateofBirth);
                    break;
                case "date_desc":
                    list = list.OrderByDescending(selectedlist => selectedlist.DateofBirth);
                    break;
                default:
                    list = list.OrderBy(selectedlist => selectedlist.DateofBirth);
                    break;
            }

            int pageSize = 5;
            return View(await PaginatedList<EmployeeData>.CreateAsync(list.AsNoTracking(), pageNumber ?? 1, pageSize));
             return View(await list.AsNoTracking().ToListAsync());
        }



     

        public async Task<IActionResult> Indexes(string sortOrder, string searchString, string currentFilter,int? pageNumber)

        {



            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

          
            var list = from selectedlist in database.Employeess
                     select selectedlist;

            if (!String.IsNullOrEmpty(searchString))
            {
                list = list.Where(selectedlist => selectedlist.UserID.Contains(searchString) || selectedlist.Name.Contains(searchString)
                                       || selectedlist.TeamName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    list = list.OrderByDescending(selectedlist => selectedlist.TeamName);
                    break;
                case "Date":
                    list = list.OrderBy(selectedlist => selectedlist.DateofBirth);
                    break;
                case "date_desc":
                    list = list.OrderByDescending(selectedlist => selectedlist.DateofBirth);
                    break;
                default:
                    list = list.OrderBy(selectedlist => selectedlist.DateofBirth);
                    break;
            }

            int pageSize = 5;
            return View(await PaginatedLists<EmployeeData>.CreateAsync(list.AsNoTracking(), pageNumber ?? 1, pageSize));
             return View(await list.AsNoTracking().ToListAsync());
        }


       
       
       
        [HttpGet]
        public IActionResult Create()
        {

            EmployeeData userdata = new EmployeeData();

            return View(userdata);
        }

        [HttpPost]
       
        public async Task<IActionResult>  Create(EmployeeData employeedata, IFormFile file)
        {
           if (ModelState.IsValid)
        {
            if (await database.Employeess.AnyAsync(x => x.UserID == employeedata.UserID))
            {
                ModelState.AddModelError("UserID", "Email ID already exists");
            }

            // Check if register number already exists
            if (await database.Employeess.AnyAsync(x => x.MobileNumber == employeedata.MobileNumber))
            {
                ModelState.AddModelError("MobileNumber", "MobileNumber number already exists");
            }
            if (await database.Employeess.AnyAsync(x => x.Name == employeedata.Name))
            {
                ModelState.AddModelError("Name", "Name already exists");
            }
            if (!ModelState.IsValid)
            {
                return View(employeedata);
            }
            
            EmployeeData userdata = new EmployeeData();
            if (file == null || file.Length == 0)
            {
                userdata.ProfilePicture = "NoImage.png";
            }
            else
            {
                string filename = System.Guid.NewGuid().ToString() + " .jpg";
                var path = Path.Combine(
                            Directory.GetCurrentDirectory(), "wwwroot", "images", filename);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                userdata.ProfilePicture = filename;

            }

        
            userdata.Name=employeedata.Name;
            userdata.UserID = employeedata.UserID;
            userdata.Password = employeedata.Password;
            userdata.Experience = employeedata.Experience;
            userdata.EmployeePackage=employeedata.EmployeePackage;
            userdata.Gender=employeedata.Gender;
            userdata.MobileNumber = employeedata.MobileNumber;
            userdata.Aadhaar=employeedata.Aadhaar;
            userdata.Address = employeedata.Address;
            userdata.TeamName = employeedata.TeamName;
            userdata.DateofBirth = employeedata.DateofBirth;
             database.Employeess.Add(userdata);
            await database.SaveChangesAsync();
            return RedirectToAction("Index");

        }
           return View(employeedata);
        }


         [HttpGet]

        public async Task<IActionResult> Edit(int? id)

        {

            if (id == null)
            {
                return NotFound();
            }

            EmployeeData userdata = await database.Employeess.Where(x => x.ID == id).FirstOrDefaultAsync();
            try{
            if (userdata == null)
            {
                return NotFound();
            }
            return View(userdata);
            }
             catch(Exception ex)
        {
         Console.WriteLine("The Error was Occured: " + ex.Message);
         return RedirectToAction("Index","Error");
        }
        }
        [HttpPost]
  
        public async Task<IActionResult> Edit(int? id,EmployeeData employeedata, IFormFile file)

        {
           if (id == null)
            {
                return NotFound();

            }



            EmployeeData userdata = await database.Employeess.Where(x => x.ID == id).FirstOrDefaultAsync();



            if (userdata == null)

            {

                return NotFound();

            }





            if (file != null )

            {



                string filename = System.Guid.NewGuid().ToString() + " .jpg";

                var path = Path.Combine(

                            Directory.GetCurrentDirectory(), "wwwroot", "images", filename);



                using (var stream = new FileStream(path, FileMode.Create))

                {

                    await file.CopyToAsync(stream);

                }



                userdata.ProfilePicture = filename;



            }
            userdata.Name=employeedata.Name;
            userdata.UserID = employeedata.UserID;
            userdata.Password = employeedata.Password;
            userdata.Experience = employeedata.Experience;
            userdata.EmployeePackage=employeedata.EmployeePackage;
            userdata.Gender=employeedata.Gender;
            userdata.MobileNumber = employeedata.MobileNumber;
            userdata.Aadhaar=employeedata.Aadhaar;
            userdata.Address = employeedata.Address;
            userdata.TeamName = employeedata.TeamName;
            userdata.DateofBirth = employeedata.DateofBirth;
            
                await database.SaveChangesAsync();
                return RedirectToAction("Index");    

        }



       
          [HttpGet("Details/{id:int}")]
         
        public async Task<IActionResult> Details(int? id)


        {

            if (id == null)

            {

                return NotFound();

Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IdentityManagement;
using IdentityManagement.Models;
using System.Diagnostics;

namespace RequestController.Controllers
{
    public class RequestController : Controller
    {
        private readonly EmployeeDataDbContext db;
        private readonly IWebHostEnvironment _environment;
        
        public RequestController(EmployeeDataDbContext context, IWebHostEnvironment environment)
        {
            db = context;
            _environment = environment;
        }
        
        public async Task<IActionResult> RequestStatus(){ 
      
        var userRequest = await db.Requestss.Where(b=>b.UserId ==Database.mail).ToListAsync();
        return View(userRequest);
        }
  
        [HttpGet]

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)

        {



            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;


            var list = from selectedlist in db.Requestss
                     select selectedlist;

            if (!String.IsNullOrEmpty(searchString))
            {
                list = list.Where(selectedlist => selectedlist.UserId.Contains(searchString) || selectedlist.Name.Contains(searchString)
                                       );
            }

            switch (sortOrder)
            {
                case "name_desc":
                    list = list.OrderByDescending(selectedlist => selectedlist.Name);
                    break;
                case "Date":
                    list = list.OrderBy(selectedlist => selectedlist.UserId);
                    break;
                case "date_desc":
                    list = list.OrderByDescending(selectedlist => selectedlist.UserId);
                    break;
                default:
                    list = list.OrderBy(selectedlist => selectedlist.UserId);
                    break;
            }

            int pageSize = 5;
            return View(await PaginatedList<Request>.CreateAsync(list.AsNoTracking(), pageNumber ?? 1, pageSize));
             return View(await list.AsNoTracking().ToListAsync());
        }



       
        [HttpGet]
        public IActionResult Create()
        {
            Request userrequest = new Request();

            return View(userrequest);
        }

        [HttpPost]
        public async Task<IActionResult>  Create(Request employeerequest, IFormFile file)
        {
            Request userrequest = new Request();
            userrequest.Name=Database.Name;
            userrequest.UserId = Database.mail;
            userrequest.request = employeerequest.request;
            userrequest.ExistingData=employeerequest.ExistingData;
            userrequest.NewData=employeerequest.NewData;
            userrequest.status="Pending";
            db.Requestss.Add(userrequest);
            await db.SaveChangesAsync();
            return RedirectToAction("Create");

        }

         [HttpGet]

        public async Task<IActionResult> Edit(int? id)

        {

            if (id == null)
            {
                return NotFound();
            }

            Request userrequest = await db.Requestss.Where(x => x.ID == id).FirstOrDefaultAsync();

            if (userrequest == null)
            {
                return NotFound();
            }
            return View(userrequest);

        }
        [HttpPost]

        public async Task<IActionResult> Edit(int? id,Request employeerequest, IFormFile file)

        {
           if (id == null)
            {
                return NotFound();

            }


            Request userrequest = await db.Requestss.Where(x => x.ID == id).FirstOrDefaultAsync();



            if (userrequest == null)

            {

                return NotFound();

            }

            // userrequest.Name=employeerequest.Name;
            // userrequest.UserId = employeerequest.UserId;
            // userrequest.request = employeerequest.request;
            // userrequest.ExistingData=employeerequest.ExistingData;
            // userrequest.NewData=employeerequest.NewData;
             userrequest.status=employeerequest.status;
            
                await db.SaveChangesAsync();
                return RedirectToAction("Index");    

        }



       

  [HttpGet]


        public async Task<IActionResult> Detail(int? id)


        {

            if (id == null)

            {

                return NotFound();

            }



            Request userrequest = await db.Requestss.Where(x => x.ID == id).FirstOrDefaultAsync();





            if (userrequest == null)

            {

                return NotFound();

            }



            return View(userrequest);

        }

  [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || db.Requestss == null)
            {
                return NotFound();
            }

            var Requestlist = await db.Requestss
                .FirstOrDefaultAsync(m => m.ID == id);
            if (Requestlist == null)
            {
                return NotFound();
            }

            return View(Requestlist );
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (db.Requestss == null)
            {
                return Problem("Entity set 'EmployeeDataDbContext.Requestss'  is null.");
            }
            var EmployeeDatas = await db.Requestss.FindAsync(id);
            if (EmployeeDatas != null)
            {
                db.Requestss.Remove(EmployeeDatas);
            }
            
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
      
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
 
    }
}

Views/EmployeeData/Create.cshtml
@model EmployeeData
@inject IHttpContextAccessor HttpContextAccessor;
@{
    ViewData["Title"] = "Create";
}


<head>
     <link rel="stylesheet" href="~/css/form.css" type="text/css"asp-append-version="true" />
    <meta http-equiv='refresh'content="10000;url=https://localhost:7087/Main/SessionExpired" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
  <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light  ">
            <div class="container-fluid">
                <img src="~/images/Elogo2.png" style="width: 5%;margin-right:30px;"  alt="LOGO">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Profile">EMPLOYEE MANAGEMENT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse  justify-content-between">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeData" asp-action="Create"><b>Add Employee</b></a> </li>
                        <li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeData" asp-action="Index"><b>Update & Delete</b></a> </li>
                        
                      </div>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end" >
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index"> <i class="fa fa-bell" style="font-size:28px;color:rgb(22, 17, 19)"></i></a>
                           
                        </li>
                        <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Profile"> <i class="fa fa-user" style="font-size:28px;color:rgb(22, 17, 19)"></i></a>
                         
                        </li>
                         <li class="nav-item">
                        
                           <a class="greeting nav-link text-dark" style="color: rgb(187, 26, 26);">  Hi  @HttpContextAccessor.HttpContext.Session.GetString("EmailId")</a>
                        </li>
                        
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="logOut"><b>Logout</b></a>
                        </li>
                    </ul>
                </div> 
                             @* <ul class="navbar-nav ">
                              <h5 class="greeting" style="color: rgb(187, 26, 26);"> Hi  @HttpContextAccessor.HttpContext.Session.GetString("EmailId")</h5>
                          </ul></div> *@
                         
                        
                  
            </div>
        </nav>
 
 <h3 style="text-align:center; color:white;margin-top:10px;margin-bottom:10px;">Add a New Employee</h3>
    <div class="container">


    

    <div class="content">
        <form asp-action="Create" enctype="multipart/form-data">
            <div class="user-details">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group input-box">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" placeholder="Enter Employee Name" class="form-control" />
                <span asp-validation-for="Name"  class="text-danger"></span>
            </div>
            
            <div class="form-group input-box">
                <label asp-for="ProfilePicture" class="control-label"></label>
                  <input type="file" name="file" />
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            </div>

            <div class="form-group input-box">
                <label asp-for="UserID" class="control-label"></label>
                <input asp-for="UserID"  placeholder="Enter Employee Email Id" class="form-control" />
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="form-group input-box">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
             <div class="form-group input-box">
                <label asp-for="EmployeePackage" class="control-label"></label>
                <input asp-for="EmployeePackage"  placeholder="Enter Employee Annual Package" class="form-control" />
                <span asp-validation-for="EmployeePackage" class="text-danger"></span>
            </div>

             <div class="form-group input-box">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender"  class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>

            <div class="form-group input-box">
                <label asp-for="Experience" class="control-label"></label>
                <input asp-for="Experience" class="form-control" />
                <span asp-validation-for="Experience" class="text-danger"></span>
            </div>
            <div class="form-group input-box">
                <label asp-for="MobileNumber" class="control-label"></label>
                <input asp-for="MobileNumber" class="form-control" />
                <span asp-validation-for="MobileNumber" class="text-danger"></span>
            </div>
             <div class="form-group input-box">
                <label asp-for="Aadhaar" class="control-label"></label>
                <input asp-for="Aadhaar" class="form-control" />
                <span asp-validation-for="Aadhaar" class="text-danger"></span>
            </div>
            <div class="form-group input-box">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group input-box">
                <label asp-for="TeamName" class="control-label"></label>
                <input asp-for="TeamName" placeholder="Enter Employee TeamName" class="form-control" />
                <span asp-validation-for="TeamName" class="text-danger"></span>
            </div>
            <div class="form-group input-box">
                <label asp-for="DateofBirth" class="control-label"></label>
                <input asp-for="DateofBirth" class="form-control" />
                <span asp-validation-for="DateofBirth" class="text-danger"></span>
            </div>
                
            <div class="form-group " style="margin-right:140px;margin-top:25px;" >
                <input type="submit" value="Create" class="btn btn-primary" />
                 <a asp-action="Index">Back to List</a>
            </div>
            </div>
            <div Class="input-box">
        
             </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}